### ISSUE TITLE
Support missing methods for UICollectionViewDataSource

### ISSUE THREAD

**Issue by 3lvis** [3lvis/DATASource#14]
```objc
// The view that is returned must be retrieved from a call to -dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;
```

**Comment by 3lvis** [comment]
Done! #20

**Comment by bonebox** [comment]
Hey @3lvis, should this be working in the latest version?  The delegate method isn't being called for me.  FYI, I was using storyboards at first, but noticed another Github issue where you said not to use storyboards, so I tried it programatically, but it's still not being called.  

Also, the readme mentions that the demo collection view project has an example for adding footers via the DataSourceDelegate, but it appears that has been removed?

**Comment by bonebox** [comment]
Ok, I got it working for both storyboard and programmatically.

First thing is the DATASource delegate needs to be set like `self.dataSource.delegate = self`.  I was already doing this, but it may not be clear to some, so might be a good idea to add that to the README (and/or the demo).

# Storyboard
For storyboard, `Section Header` has to be selected under Flow layout:

<img width="243" alt="screen shot 2016-02-23 at 6 12 31 pm" src="https://cloud.githubusercontent.com/assets/1120504/13271224/4420540e-da59-11e5-925d-dcfa7a11514f.png">

# Programmatically
Either the `headerReferenceSize` property of your UICollectionViewFlowLayout needs to be set (i.e. `(self.collectionViewLayout as! UICollectionViewFlowLayout).headerReferenceSize = CGSizeMake(300, 44)`), or your UICollectionViewController needs to adopt `UICollectionViewDelegateFlowLayout` and then implement  `    optional public func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize`.
